//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Application.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\Images\BlueCar.png.
        /// </summary>
        internal static string BlueCar {
            get {
                return ResourceManager.GetString("BlueCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\Images\BlueCarBroken.png.
        /// </summary>
        internal static string BlueCarBroken {
            get {
                return ResourceManager.GetString("BlueCarBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\Images\Corner.png.
        /// </summary>
        internal static string Corner {
            get {
                return ResourceManager.GetString("Corner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\Images\Finish.png.
        /// </summary>
        internal static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\Images\GreenCar.png.
        /// </summary>
        internal static string GreenCar {
            get {
                return ResourceManager.GetString("GreenCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\Images\GreenCarBroken.png.
        /// </summary>
        internal static string GreenCarBroken {
            get {
                return ResourceManager.GetString("GreenCarBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\Images\GreyCar.png.
        /// </summary>
        internal static string GreyCar {
            get {
                return ResourceManager.GetString("GreyCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\Images\GreyCarBroken.png.
        /// </summary>
        internal static string GreyCarBroken {
            get {
                return ResourceManager.GetString("GreyCarBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\Images\RedCar.png.
        /// </summary>
        internal static string RedCar {
            get {
                return ResourceManager.GetString("RedCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\Images\RedCarBroken.png.
        /// </summary>
        internal static string RedCarBroken {
            get {
                return ResourceManager.GetString("RedCarBroken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\Images\Start.png.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\Images\Straight.png.
        /// </summary>
        internal static string Straight {
            get {
                return ResourceManager.GetString("Straight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\Images\YellowCar.png.
        /// </summary>
        internal static string YellowCar {
            get {
                return ResourceManager.GetString("YellowCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .\Images\YellowCarBroken.png.
        /// </summary>
        internal static string YellowCarBroken {
            get {
                return ResourceManager.GetString("YellowCarBroken", resourceCulture);
            }
        }
    }
}
